# Generated by Django 5.0.7 on 2024-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zip_number',
            field=models.CharField(max_length=50),
        ),
    ]
